# SPDX-FileCopyrightText: 2019 Jana Iyengar, Marten Seemann
# SPDX-License-Identifier: Apache-2.0

# This file is taken from https://github.com/marten-seemann/quic-interop-runner
# and has been modified by the tls-interop-runner Authors.

name: Deploy website
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TLS_INTEROP_HOST }}
          username: ${{ secrets.TLS_INTEROP_USERNAME }}
          key: ${{ secrets.TLS_INTEROP_SSH_KEY }}
          port: ${{ secrets.TLS_INTEROP_SSH_PORT }}
          source: website/
          target: ${{ secrets.TLS_INTEROP_WEBSITE_DIR }}/website/
          strip_components: 1
      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TLS_INTEROP_HOST }}
          username: ${{ secrets.TLS_INTEROP_USERNAME }}
          key: ${{ secrets.TLS_INTEROP_SSH_KEY }}
          port: ${{ secrets.TLS_INTEROP_SSH_PORT }}
          script: sudo systemctl restart caddy
